<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA2kGL10\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA2kGL10/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA2kGL10.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA2kGL10\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA2kGL10\App_KernelDevDebugContainer([
    'container.build_hash' => 'A2kGL10',
    'container.build_id' => '11b05381',
    'container.build_time' => 1700212262,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA2kGL10');
